server:
  port: 8080
spring:
  application:
    name: test-spring-boot
  redis:
    host: 172.18.5.191
    database: 8
    password: 123456
    port: 6379
ken:
  cache:
    cache-prefix: ken
    caffeine:
      expireAfterAccess: 500000
    redis:
      defaultExpiration: 600000
logging:
  level:
    root: info
    pers.hui.spring: debug